"""p7_accounting_plugin

Revision ID: 091db215b2c4
Revises: c3d4e5f6a7b8
Create Date: 2026-05-25 14:29:12.212783

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '091db215b2c4'
down_revision: str | None = 'c3d4e5f6a7b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acct_budgets',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_table('acct_transactions',
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acct_transactions_created_at'), 'acct_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_acct_transactions_family_id'), 'acct_transactions', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acct_transactions_family_id'), table_name='acct_transactions')
    op.drop_index(op.f('ix_acct_transactions_created_at'), table_name='acct_transactions')
    op.drop_table('acct_transactions')
    op.drop_table('acct_budgets')
    # ### end Alembic commands ###
