"""p3_1_plugin_platform

Revision ID: 3e9daa1cfecc
Revises: 0d06da1c9575
Create Date: 2026-05-23 09:07:19.697027

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e9daa1cfecc'
down_revision: str | None = '0d06da1c9575'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('current_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anniv_dates',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('is_lunar', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anniv_dates_family_id'), 'anniv_dates', ['family_id'], unique=False)
    op.create_table('installed_plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('cw', sa.Integer(), nullable=False),
    sa.Column('ch', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('installed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'plugin_id', name='uq_installed_family_plugin')
    )
    op.create_index(op.f('ix_installed_plugins_family_id'), 'installed_plugins', ['family_id'], unique=False)
    op.create_index(op.f('ix_installed_plugins_plugin_id'), 'installed_plugins', ['plugin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installed_plugins_plugin_id'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_family_id'), table_name='installed_plugins')
    op.drop_table('installed_plugins')
    op.drop_index(op.f('ix_anniv_dates_family_id'), table_name='anniv_dates')
    op.drop_table('anniv_dates')
    op.drop_table('plugins')
    # ### end Alembic commands ###
