"""p12 recipe tags

Revision ID: 4a4ada22c6a9
Revises: 6629a177be6d
Create Date: 2026-05-26 14:03:09.409975

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4a4ada22c6a9'
down_revision: str | None = '6629a177be6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'name', name='uq_recipe_tag')
    )
    op.create_index(op.f('ix_recipe_tags_family_id'), 'recipe_tags', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_tags_family_id'), table_name='recipe_tags')
    op.drop_table('recipe_tags')
    # ### end Alembic commands ###
