"""p16 memory plugin

Revision ID: 5777670d1df9
Revises: c9d8e7f6a5b4
Create Date: 2026-05-27 14:07:38.470753

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5777670d1df9'
down_revision: str | None = 'c9d8e7f6a5b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_memories',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_memories_created_by'), 'memory_memories', ['created_by'], unique=False)
    op.create_index(op.f('ix_memory_memories_event_date'), 'memory_memories', ['event_date'], unique=False)
    op.create_index(op.f('ix_memory_memories_family_id'), 'memory_memories', ['family_id'], unique=False)
    op.create_table('memory_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_comments_family_id'), 'memory_comments', ['family_id'], unique=False)
    op.create_index(op.f('ix_memory_comments_memory_id'), 'memory_comments', ['memory_id'], unique=False)
    op.create_table('memory_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_media_family_id'), 'memory_media', ['family_id'], unique=False)
    op.create_index(op.f('ix_memory_media_memory_id'), 'memory_media', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_media_memory_id'), table_name='memory_media')
    op.drop_index(op.f('ix_memory_media_family_id'), table_name='memory_media')
    op.drop_table('memory_media')
    op.drop_index(op.f('ix_memory_comments_memory_id'), table_name='memory_comments')
    op.drop_index(op.f('ix_memory_comments_family_id'), table_name='memory_comments')
    op.drop_table('memory_comments')
    op.drop_index(op.f('ix_memory_memories_family_id'), table_name='memory_memories')
    op.drop_index(op.f('ix_memory_memories_event_date'), table_name='memory_memories')
    op.drop_index(op.f('ix_memory_memories_created_by'), table_name='memory_memories')
    op.drop_table('memory_memories')
    # ### end Alembic commands ###
