"""p11 recipe cover

Revision ID: 6629a177be6d
Revises: 2978fdfc85e2
Create Date: 2026-05-26 13:32:22.251724

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6629a177be6d'
down_revision: str | None = '2978fdfc85e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_recipes', sa.Column('cover_storage_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('recipe_recipes', sa.Column('cover_content_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # server_default backfills existing rows (NOT NULL on a populated table).
    op.add_column('recipe_recipes', sa.Column('cover_version', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_recipes', 'cover_version')
    op.drop_column('recipe_recipes', 'cover_content_type')
    op.drop_column('recipe_recipes', 'cover_storage_key')
    # ### end Alembic commands ###
