"""p34 travel plugin

Creates travel_trips: one row per travel record — a city (name + lng/lat), a
caption, the original photo, and an optional AI-restyled image (img2img). The
chosen column records which image is the cover; both blobs are kept.

Revision ID: 8fc2957c819d
Revises: f5a6b7c8d9e0
Create Date: 2026-06-08 19:41:06.191034

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8fc2957c819d'
down_revision: str | None = 'f5a6b7c8d9e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('city_lng', sa.Float(), nullable=False),
    sa.Column('city_lat', sa.Float(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('original_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_content_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_height', sa.Integer(), nullable=True),
    sa.Column('ai_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_content_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('ai_prompt', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('ai_style', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('chosen', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_trips_family_id'), 'travel_trips', ['family_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_travel_trips_family_id'), table_name='travel_trips')
    op.drop_table('travel_trips')
